//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinclairCC.MakeMeAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinclairCC.MakeMeAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Adding the user back to the Administrators group. 的本地化字符串。
        /// </summary>
        internal static string AddingUserBackToAdministrators {
            get {
                return ResourceManager.GetString("AddingUserBackToAdministrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding user {0} ({1}) to the Administrators group returned error code {2}. 的本地化字符串。
        /// </summary>
        internal static string AddingUserReturnedError {
            get {
                return ResourceManager.GetString("AddingUserReturnedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception 的本地化字符串。
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local admins group SID is null. 的本地化字符串。
        /// </summary>
        internal static string LocalAdminsGroupSIDIsNull {
            get {
                return ResourceManager.GetString("LocalAdminsGroupSIDIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local machine context is null. 的本地化字符串。
        /// </summary>
        internal static string LocalMachineContextIsNull {
            get {
                return ResourceManager.GetString("LocalMachineContextIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make Me Admin service stopped 的本地化字符串。
        /// </summary>
        internal static string RemovalReasonServiceStopped {
            get {
                return ResourceManager.GetString("RemovalReasonServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout elapsed 的本地化字符串。
        /// </summary>
        internal static string RemovalReasonTimeout {
            get {
                return ResourceManager.GetString("RemovalReasonTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string RemovalReasonUnknown {
            get {
                return ResourceManager.GetString("RemovalReasonUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User logged off 的本地化字符串。
        /// </summary>
        internal static string RemovalReasonUserLogoff {
            get {
                return ResourceManager.GetString("RemovalReasonUserLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User requested removal 的本地化字符串。
        /// </summary>
        internal static string RemovalReasonUserRequest {
            get {
                return ResourceManager.GetString("RemovalReasonUserRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing the user from Make Me Admin&apos;s list. 的本地化字符串。
        /// </summary>
        internal static string RemovingUserFromList {
            get {
                return ResourceManager.GetString("RemovingUserFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing user {0} ({1}) from the Administrators group returned error code {1}. 的本地化字符串。
        /// </summary>
        internal static string RemovingUserReturnedError {
            get {
                return ResourceManager.GetString("RemovingUserReturnedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Account 的本地化字符串。
        /// </summary>
        internal static string UnknownAccount {
            get {
                return ResourceManager.GetString("UnknownAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User {0} ({1}) added to the Administrators group. 的本地化字符串。
        /// </summary>
        internal static string UserAddedToAdminsGroup {
            get {
                return ResourceManager.GetString("UserAddedToAdminsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User {0} ({1}) removed from the Administrators group. Reason: {2}. 的本地化字符串。
        /// </summary>
        internal static string UserRemoved {
            get {
                return ResourceManager.GetString("UserRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User {0} ({1}) has been removed from the Administrators group by an outside process. 的本地化字符串。
        /// </summary>
        internal static string UserRemovedByOutsideProcess {
            get {
                return ResourceManager.GetString("UserRemovedByOutsideProcess", resourceCulture);
            }
        }
    }
}
