//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinclairCC.MakeMeAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinclairCC.MakeMeAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Ready. 的本地化字符串。
        /// </summary>
        public static string ApplicationIsReady {
            get {
                return ResourceManager.GetString("ApplicationIsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make Me Admin 的本地化字符串。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking administrator status... 的本地化字符串。
        /// </summary>
        public static string CheckingAdminStatus {
            get {
                return ResourceManager.GetString("CheckingAdminStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Message 的本地化字符串。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grant Me Administrator Rights 的本地化字符串。
        /// </summary>
        public static string GrantRightsButtonText {
            get {
                return ResourceManager.GetString("GrantRightsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon SecurityLock {
            get {
                object obj = ResourceManager.GetObject("SecurityLock", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Stack Trace 的本地化字符串。
        /// </summary>
        public static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are now a member of the {0} group. 的本地化字符串。
        /// </summary>
        public static string UIMessageAddedToGroup {
            get {
                return ResourceManager.GetString("UIMessageAddedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding you to the {0} group. 的本地化字符串。
        /// </summary>
        public static string UIMessageAddingToGroup {
            get {
                return ResourceManager.GetString("UIMessageAddingToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You already have administrator rights. 的本地化字符串。
        /// </summary>
        public static string UIMessageAlreadyHaveRights {
            get {
                return ResourceManager.GetString("UIMessageAlreadyHaveRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please make sure the Make Me Admin service is running. 的本地化字符串。
        /// </summary>
        public static string UIMessageEnsureServiceRunning {
            get {
                return ResourceManager.GetString("UIMessageEnsureServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while adding you to the Administrators group. 的本地化字符串。
        /// </summary>
        public static string UIMessageErrorWhileAdding {
            get {
                return ResourceManager.GetString("UIMessageErrorWhileAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while removing you from the Administrators group. 的本地化字符串。
        /// </summary>
        public static string UIMessageErrorWhileRemoving {
            get {
                return ResourceManager.GetString("UIMessageErrorWhileRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are no longer a member of the {0} group. 的本地化字符串。
        /// </summary>
        public static string UIMessageRemovedFromGroup {
            get {
                return ResourceManager.GetString("UIMessageRemovedFromGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing you from the {0} group. 的本地化字符串。
        /// </summary>
        public static string UIMessageRemovingFromGroup {
            get {
                return ResourceManager.GetString("UIMessageRemovingFromGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not authorized to use this application. 的本地化字符串。
        /// </summary>
        public static string UIMessageUnauthorized {
            get {
                return ResourceManager.GetString("UIMessageUnauthorized", resourceCulture);
            }
        }
    }
}
